### ISSUE TITLE
録画したファイルを共有アップする。

### ISSUE THREAD

**Issue by kazucharo** [itomakiweb-corp/puzzle-terms#21]
ファイル形式の変更が必要かも。

**Comment by kazucharo** [comment]
GitかGoogleドライブか。LINEでも共有できる可能性はあるかも。

**Comment by bac0907** [comment]
Googleドライブのアプリを使用し、「zz1-events」内の「20200119-programming」に８秒程度の動画を保存し、共有を確認した。
見られる人は細田兄弟とべー。
