### ISSUE TITLE
第三回の内容を決める

### ISSUE THREAD

**Issue by bac0907** [itomakiweb-corp/puzzle-terms#49]

**Comment by bac0907** [comment]
第三回の内容
自分でプログラミングを組んでもらう場合
（ランダムにお寿司が流れるか、）決めた順番通りにお寿司が流れるか

最初にプログラムを実行する
回転寿司なのに一つも食べられない。しかも一つも食べてないのに満腹だと言う。皆んなでプログラムを直そう！

あらかじめ好きな食べ物によって食べる、食べないを子供に決めてもらい、プログラムに反映させていく。
「まぐろは好き？食べる？食べない？」
「いかは好き？食べる？食べない？」
その後、満腹について聞く。
「何皿食べたらお腹いっぱいになる？５皿？１０皿？」
「まぐろといかは食べるんだよね？じゃあそれを食べたらもうお腹いっぱいになるかな？」
条件分岐として満腹になる枚数を入力し、プログラムを実行する。
画面に一枚ずつ、（ランダムに決められた？）お皿に乗ったお寿司等が出て来る。その都度、「まぐろ　は　食べる！」、「サーモン　は　食べない！」など先ほどの選択肢に合わせてお皿を取るか取らないか画面のキャラが選択する。全部で１０皿程度？お寿司が出てきたら

お寿司屋さんが目の前にたってる
レーンをお寿司が流れてくる

命令ブロックに「食べる」、「食べない」、「まぐろがきたら」、「サーモンがきたら」などの各お寿司を作る。

**Comment by bac0907** [comment]
2/4
構成を相談する。
回転寿司で条件分岐で１時間弱使う。

第二回で画像を選ぶことを学んだはず。
第三回では新しいメニューを追加する事を教えるとすると、必要な事は、
画像を（自分で）用意する、
（好きなものを検索する）、
（画像をアップロードする）、
画像の名前を（自分で）変更する、
（自分で）メニューを追加する、


それぞれの子供達の目標を確認するか
各スタッフの支援内容を明確化するか

**Comment by kazucharo** [comment]
[第3回のスライド：印刷用.pdf](https://github.com/itomakiweb-corp/puzzle-terms/files/4185857/3.pdf)
[第3回のスライド：印刷用.pptx](https://github.com/itomakiweb-corp/puzzle-terms/files/4185859/3.pptx)
[フローチャートの設計図プリント3.docx](https://github.com/itomakiweb-corp/puzzle-terms/files/4185862/3.docx)
[「もし」のテーブル用のプリント：両面印刷（短辺で）.pptx](https://github.com/itomakiweb-corp/puzzle-terms/files/4185863/default.pptx)
