### ISSUE TITLE
つむぐプログラミング教室のパワーポイントを作る。

### ISSUE THREAD

**Issue by kazucharo** [itomakiweb-corp/puzzle-terms#6]
- [ ] テキスト、フロー、画像、動画
- [ ] 作ったものを4回分に分ける。

**Comment by kazucharo** [comment]
[つむぐ：子どもプログラミング教室.pptx](https://github.com/bac0907/puzzle-terms/files/3828353/default.pptx)

**Comment by kazucharo** [comment]
↑ めっちゃ途中ですが、共有しておくといいかと。

**Comment by bac0907** [comment]
確認しました！

**Comment by kazucharo** [comment]
[子どもプログラミング教室：べー達に見てもらう用.pptx](https://github.com/itomakiweb-corp/puzzle-terms/files/4014997/default.pptx)

**Comment by bac0907** [comment]
https://develop.viscuit.com/env/schoolopen3.html?sid=64468830

**Comment by bac0907** [comment]
・タイトル（三段で）

・お約束事を確認

・学校でプログラミング教育開始

・プログラミング的思考とは

・ジェーソンロボット動画を観て失敗を確認（ジェーソンの動画のどれを選ぶか）

・学習テーマとねらい
魚を出す、計画、思った通りの動き、自由に試すよと伝える

・ビスケットの紹介

・これから使う言葉の説明、紹介
命令、実行、（）

・ビスケットの画面紹介
①絵に命令を出す場所、②絵を置いて動かす場所、

・①について説明
メガネは左から右へ、絵を描く、世界へアップロードはまだ押さないで（送ると絵が消える）、この画面を消す、向きを変える、メニュー、

・パレットの画面紹介
色を選ぶ、色を調整（変える）、色の太さ、色の濃さ、（保存）、（消去）

・魚をまっすぐ動かすには？
メガネを置く、絵を描く、描いた絵をメガネに入れる、描いた絵を左の画面に置く
（パワポでやるか、ビスケットで実際にやってみるか）
（ビスケットをパソコンでやってみるか、タブレットでやってみるか）
（ひとりでつくるで行うか、みんなでつくるかで行うか）

・（例題３つ用意か）

・設計しよう
プリント配る

・休憩

・プログラミングスタート

・みんなの作品を見てみよう

・終了

**Comment by kazucharo** [comment]
[プログラミングの設計図プリント.docx](https://github.com/itomakiweb-corp/puzzle-terms/files/4015699/default.docx)

**Comment by kazucharo** [comment]
[子どもプログラミング教室：べー達に見てもらう用.pptx](https://github.com/itomakiweb-corp/puzzle-terms/files/4015701/default.pptx)

**Comment by kazucharo** [comment]
[プログラミングの設計図プリント.docx](https://github.com/itomakiweb-corp/puzzle-terms/files/4015859/default.docx)
[子どもプログラミング教室：べー達に見てもらう用.pptx](https://github.com/itomakiweb-corp/puzzle-terms/files/4015860/default.pptx)

↑現状の最新のものです。

**Comment by kazucharo** [comment]
ジェーソン失敗動画、べーさんにお願いしたいです！
１／４に間に合うなら、貼り付けておきます。

**Comment by bac0907** [comment]
https://scratch.mit.edu/projects/357065131/editor

**Comment by kazucharo** [comment]
[子どもプログラミング教室：べー達に見てもらう用：第2回.pdf](https://github.com/itomakiweb-corp/puzzle-terms/files/4023414/2.pdf)
[子どもプログラミング教室：べー達に見てもらう用：第2回.pptx](https://github.com/itomakiweb-corp/puzzle-terms/files/4023415/2.pptx)

↑できているところまで。
Macなら、PDFのほうが方が見やすいかも。

**Comment by kazucharo** [comment]
[子どもプログラミング教室：べー達に見てもらう用：第4回.pdf](https://github.com/itomakiweb-corp/puzzle-terms/files/4025869/4.pdf)
[子どもプログラミング教室：べー達に見てもらう用：第3回.pdf](https://github.com/itomakiweb-corp/puzzle-terms/files/4025870/3.pdf)
[子どもプログラミング教室：べー達に見てもらう用：第4回.pptx](https://github.com/itomakiweb-corp/puzzle-terms/files/4025871/4.pptx)
[子どもプログラミング教室：べー達に見てもらう用：第3回.pptx](https://github.com/itomakiweb-corp/puzzle-terms/files/4025872/3.pptx)

枠組を作っておきました。
たたき台などに使ってください。

**Comment by bac0907** [comment]
懸念事項
- [ ] パワポが映るか確認する
- [ ] 子供達の席順の確認をする
左からかえで、しゅう、けい、まこと、ゆたか、つかさ
高橋さんはけいくん、
まりこさんはしゅうくん、かえでさん
てらさんは誠くん、豊くん、つかさくん

- [ ] 使うタブレット、パソコンを充電しておく
- [ ] スタッフ用のプリント一式を用意しておく
- [ ] 各つくえ用のプリント一式を用意しておく
- [ ] 子供たち用のプリント一式を用意しておく
- [ ] スタッフがつくテーブル、場所を確認する
- [ ] セッティングしたら全体の写真を撮っておく
- [ ] みんなが取り組んでる様子を写真に撮っておく
