### ISSUE TITLE
why プログラミングを視聴して、要素を抽出する

### ISSUE THREAD

**Issue by kazucharo** [itomakiweb-corp/puzzle-terms#7]
- [ ] 使える部分をパワーポイントに載せる。
- [ ] 繰り返しと条件分岐が練習出来そうな回があるか探す。
- [x] まず第一回を視聴する。
- [x] 第一回の内容を抽出し、コメントする。

**Comment by bac0907** [comment]
天才プログラマーのラムと弟のプログ、新人のジェイソンの３人で構成されてる。
scratchワールドにバグが出てくるたびに直す
ジェイソンはscratchワールドに出入りできる。
第一話のミッションは、壊れた魚を動かせ。
学ぶ事は、キャラクターを動かす事と、アニメーションさせる事。
すでに画面上で左右に行き来していたイカから学ぶ。
学ぶ命令は「🏳をクリックされたとき」、「３歩動かす」、「端まで着いたら跳ね返る」、「ずっと（繰り返す）」、「回転方法を左右のみにする」である。
↑ここまでで５分。

**Comment by bac0907** [comment]
ジェイソンをプログラミング、画面の右上には「順次」。
画面には棒を持ったジェイソンとスイカ。
画面左に命令が出てくる。出てくる命令は、
「右足を一歩出す」、
「左足を一歩出す」、
「両手を振り下ろす」、
「右足を一歩出す」、
「左足を一歩出す」、
「ヤーとさけぶ」となっている。
クリック音と共にジェイソンが動き出す。スイカ割りは失敗。
画面の黒子が「両手を振り下ろす」を一番最後にする。
クリック音と共にジェイソンが動き出す。スイカ割りは成功。
↑ここまでで１分１５秒程度。

次の画面は、テーマの「ムーンウォーク」とジェイソンと命令ボタン。命令は、
「左かかとを下げ、右かかとを上げる」、
「右足に体重をのせる」、
「左足を後ろにすべらせる」、
「右かかとを下げ、左かかとを上げる」、
「左足に体重をのせる」、
「右足を後ろにすべらせる」となっている。
クリック音と共にジェイソンがゆっくりとムーンウォークをする。
これで１５秒程度。
全体として１分３０秒ほど。

**Comment by bac0907** [comment]
後半、魚を生き生きとさせる。
「コスチューム」から魚の画像を変更できる事を学ぶ。
命令は「次のコスチュームにする」。３歩進む毎に口を開けたり閉じたりする魚に変更される。歩くヤドカリの登場、ジェイソンの1ボケが入る。番組HPからこの世界へいけるとの誘導。
ここまでで２分。

**Comment by bac0907** [comment]
scratchを使用した作品、製作者のインタビューを紹介して番組終了。
これは４０秒ほど。

**Comment by bac0907** [comment]
第二回は「おかしな踊りを直せ」。
学ぶ事は「６０（ド）の音符を１拍鳴らす」、「１拍休む」、「キラキラオーケストラの音を鳴らす」、コスチュームの変更を「0.25拍休む」、「色の効果を２５ずつ変える」、「魚眼レンズの効果を２５ずつ変える」、「画像効果をなくす」。

**Comment by bac0907** [comment]
いったんclosed.
