### ISSUE TITLE
第二回本番の内容を考える（特に後半）

### ISSUE THREAD

**Issue by bac0907** [itomakiweb-corp/puzzle-terms#72]
第二回の後半の内容について

・自由にして発表して終わり

・繰り返し動くものの数字だけ変える、を学ぶ
（◯歩動かす、◯度回す、大きさを◯ずつ変える等）

・音を選択する、を学ぶ

・アカウント、パスワードを作成し、プリント等で持ち帰る

・踊るキャラを見て、プログラミングを組ませ、実際の動きと違うことを学ぶ
・◯秒待つ、を学ぶ
・コスチュームを選択する、を学ぶ

**Comment by kazucharo** [comment]
完成なのでクローズ。
