### ISSUE TITLE
当日用の配布プリントを作る。

### ISSUE THREAD

**Issue by kazucharo** [itomakiweb-corp/puzzle-terms#9]
概要などのレジュメや、スライドの配布資料もあり。

**Comment by kazucharo** [comment]
[つむぐ：子どもプログラミング教室のレジュメ.docx](https://github.com/bac0907/puzzle-terms/files/3828431/default.docx)

**Comment by kazucharo** [comment]
これまた、めっちゃ途中ですが！

**Comment by bac0907** [comment]
確認しました！

**Comment by kazucharo** [comment]
当日の配布資料の用意は進めている。
相談の中で変更もあるので、ここでクローズ。
